FROM amazonlinux:2

# yum update & install
RUN yum update -y \
    && yum install \
        zip \
        unzip \
        jq \
        -y

# install aws cli v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install

COPY ./test.sh /tmp

ENTRYPOINT [ "bash /tmp/test.sh" ]